// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: pjtdedwjaifnjmxhhhbo

class SupabaseConfig {
  static const String supabaseUrl = 'https://pjtdedwjaifnjmxhhhbo.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqdGRlZHdqYWlmbmpteGhoaGJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUyNzAzMjEsImV4cCI6MjA4MDg0NjMyMX0.dpCcMlwng_stndGC4Xe7f8LT6IwlKOPeDlrjFG3JB7w';
}
