// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: dnwwnmfqevayvmvzfnfx

class SupabaseConfig {
  static const String supabaseUrl = 'https://dnwwnmfqevayvmvzfnfx.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRud3dubWZxZXZheXZtdnpmbmZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUyNTUxMzksImV4cCI6MjA4MDgzMTEzOX0.OCCLKxbNJUBOwtfRTl39l2jsDTjh4BMPESWhIz1oZjY';
}
